"""Jazzmin admin theme configuration for Popy POS."""

JAZZMIN_SETTINGS = {
    "site_title": "Popy POS Admin",
    "site_header": "Popy POS",
    "site_brand": "Popy POS",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Welcome to Popy POS",
    "copyright": "Popy POS",
    "search_model": [
        "accounts.User",
        "shops.Shop",
        "catalog.Product",
        "parties.Customer",
        "parties.Supplier",
    ],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {
            "name": "Open POS",
            "url": "http://localhost:5173",
            "new_window": True,
        },
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "shops",
        "accounts",
        "catalog",
        "parties",
        "inventory",
        "purchasing",
        "sales",
        "returns",
        "app_settings",
        "auth",
        "token_blacklist",
    ],
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "accounts": "fas fa-users-cog",
        "accounts.user": "fas fa-user-tie",
        "shops": "fas fa-store",
        "shops.shop": "fas fa-store-alt",
        "catalog": "fas fa-tags",
        "catalog.category": "fas fa-folder",
        "catalog.product": "fas fa-box",
        "parties": "fas fa-address-book",
        "parties.customer": "fas fa-user-friends",
        "parties.supplier": "fas fa-truck",
        "inventory": "fas fa-warehouse",
        "inventory.stocktransaction": "fas fa-exchange-alt",
        "inventory.stockadjustment": "fas fa-sliders-h",
        "purchasing": "fas fa-shopping-cart",
        "purchasing.purchase": "fas fa-file-invoice",
        "sales": "fas fa-cash-register",
        "sales.sale": "fas fa-receipt",
        "returns": "fas fa-undo",
        "returns.salesreturn": "fas fa-undo-alt",
        "returns.purchasereturn": "fas fa-reply",
        "app_settings": "fas fa-cog",
        "app_settings.notificationsettings": "fas fa-bell",
        "token_blacklist": "fas fa-ban",
        "token_blacklist.blacklistedtoken": "fas fa-key",
        "token_blacklist.outstandingtoken": "fas fa-key",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "shops.shop": "horizontal_tabs",
        "accounts.user": "collapsible",
        "app_settings.notificationsettings": "collapsible",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
