# Generated by Django 5.2.14 on 2026-09-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], db_index=True, default='FREE', max_length=16),
        ),
    ]
