# Generated by Django 5.2.14 on 2026-08-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_multishop'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_shop_id_02eca0_idx',
            old_name='catalog_pro_shop_name_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_shop_id_80b88b_idx',
            old_name='catalog_pro_shop_cat_idx',
        ),
    ]
