# Generated by Django 5.2.14 on 2026-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_catalog_pro_shop_name_idx_catalog_pro_shop_id_02eca0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
