# Generated by Django 5.2.14 on 2026-09-05 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField(db_index=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(help_text='Shop at the time attendance was marked (historical integrity).', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attendance_date', '-marked_at'],
                'indexes': [models.Index(fields=['shop', 'attendance_date'], name='attendance__shop_id_c454b2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'attendance_date'), name='uniq_attendance_user_date')],
            },
        ),
    ]
