# Generated by Django 5.2.14 on 2026-09-05 10:00

from django.db import migrations, models


def copy_marked_at_to_clock_in(apps, schema_editor):
    Attendance = apps.get_model("attendance", "Attendance")
    for row in Attendance.objects.all().iterator():
        marked = getattr(row, "marked_at", None)
        if marked and not row.clock_in_at:
            row.clock_in_at = marked
            row.save(update_fields=["clock_in_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="clock_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="clock_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_marked_at_to_clock_in, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="attendance",
            name="marked_at",
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-attendance_date", "-clock_in_at"]},
        ),
    ]
