import { ROLES, type Role } from './roles';

/**
 * Granular permissions used across the app. Components are gated using the
 * <PermissionGuard /> component or the usePermissions() hook.
 */
export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  // Products
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  // Categories
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_MANAGE: 'CATEGORY_MANAGE',

  // Inventory
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',

  // Suppliers
  SUPPLIER_VIEW: 'SUPPLIER_VIEW',
  SUPPLIER_MANAGE: 'SUPPLIER_MANAGE',

  // Customers
  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_MANAGE: 'CUSTOMER_MANAGE',

  // Purchases
  PURCHASE_VIEW: 'PURCHASE_VIEW',
  PURCHASE_MANAGE: 'PURCHASE_MANAGE',

  // Sales / POS
  POS_ACCESS: 'POS_ACCESS',
  POS_CHECKOUT_SEND_EMAIL: 'POS_CHECKOUT_SEND_EMAIL',
  POS_CHECKOUT_SEND_SMS: 'POS_CHECKOUT_SEND_SMS',
  SALE_VIEW: 'SALE_VIEW',
  SALE_CREATE: 'SALE_CREATE',

  // Returns
  RETURN_VIEW: 'RETURN_VIEW',
  RETURN_MANAGE: 'RETURN_MANAGE',

  // Users
  USER_VIEW: 'USER_VIEW',
  USER_MANAGE: 'USER_MANAGE',

  // Reports
  REPORT_VIEW: 'REPORT_VIEW',

  // Settings (super admin only)
  SETTINGS_MANAGE: 'SETTINGS_MANAGE',

  // Shops (super admin only)
  SHOP_MANAGE: 'SHOP_MANAGE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

/**
 * Default role -> permission mapping. The backend remains the source of truth;
 * this map is a sensible client-side fallback when a user object does not carry
 * an explicit permission list.
 */
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.CATEGORY_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.SUPPLIER_MANAGE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_MANAGE,
    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_MANAGE,
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.POS_CHECKOUT_SEND_EMAIL,
    PERMISSIONS.POS_CHECKOUT_SEND_SMS,
    PERMISSIONS.SALE_VIEW,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.RETURN_VIEW,
    PERMISSIONS.RETURN_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,
  ],
  [ROLES.CASHIER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_MANAGE,
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.POS_CHECKOUT_SEND_EMAIL,
    PERMISSIONS.POS_CHECKOUT_SEND_SMS,
    PERMISSIONS.SALE_VIEW,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.RETURN_VIEW,
  ],
  [ROLES.INVENTORY_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.CATEGORY_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.SUPPLIER_MANAGE,
    PERMISSIONS.PURCHASE_VIEW,
    PERMISSIONS.PURCHASE_MANAGE,
  ],
};
